site_name: dorm-launch-django
site_description: Create, plan, launch great boarding events.
repo_url: https://github.com/tylerhuntington222/dorm-launch-django
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/tylerhuntington222">tylerhuntington222</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
